version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    environment:
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200
    networks:
      - app-network

volumes:
  es_data:

networks:
  app-network:
